POST http://localhost:3000/auth/registerAccount
Content-Type: application/json

{
    "username": "test6",
    "email": "test6@gmail.com",
    "nickname": "testName",
    "password": "test6"
}

###
POST http://localhost:3000/auth/loginAccount
Content-Type: application/json

{
    "email": "test6@gmail.com",
    "password": "working"
}

###
GET http://localhost:3000/auth/getAccount

###
GET http://localhost:3000/auth/getAccount/f31338c7-981d-43a6-b68c-78cab22948ca
Content-Type: application/json

{
    "refId": "f31338c7-981d-43a6-b68c-78cab22948ca"
}

###
GET http://localhost:3000/auth/getToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdDYiLCJpYXQiOjE3MTUwMDEzMTgsImV4cCI6MTcxNTAwMTM3OH0.1JlRj6x2qK7e97pa3EXtXoiYheguj73mncYAnU7WsT0

###