POST http://localhost:3000/auth/registerAccount
Content-Type: application/json

{
    "username": "test6",
    "email": "test6@gmail.com",
    "nickname": "testName",
    "password": "test6"
}

###
POST http://localhost:3000/auth/loginAccount
Content-Type: application/json

{
    "email": "test6@gmail.com",
    "password": "working"
}

###
GET http://localhost:3000/auth/getAccount

###
GET http://localhost:3000/auth/getAccount/f31338c7-981d-43a6-b68c-78cab22948ca
Content-Type: application/json

{
    "refId": "f31338c7-981d-43a6-b68c-78cab22948ca"
}

###
GET http://localhost:3000/auth/getToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdDYiLCJpYXQiOjE3MTIwNDE5MzEsImV4cCI6MTcxMjA0MTk5MX0.CG_nVPgwFvWmmoLtnSZq5SmU9x2fgLKxXM1ViEte5lI

###
POST http://localhost:3000/auth/refreshToken
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiJ9.dGVzdDY.TdW8dWZigBQcc2UB8eQWwQQHCiGa3pyxQ5-v_OXxY_g"
}

###
PATCH http://localhost:3000/auth/editAccount/65786f07e4ecfebd2945e336
Content-Type: application/json

{

    "username": "sherwynd627",
    "email": "sherwynd627@gmail.com"
}
###

DELETE http://localhost:3000/auth/deleteAccount/6578763b811a538863d71d04

###
DELETE http://localhost:3000/auth/logoutAccount
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RBZ2FpbiIsImlhdCI6MTcwMjgwNTkxOX0.EKd16-rY_DjraEzZ4GZUAyxpFdETJTQTq5-NbKPIABI"
}

###

GET http://localhost:3000/auth/findUser/f31338c7-981d-43a6-b68c-78cab22948ca
Content-Type: application/json

{
    "username": "test6"
}
###

POST http://localhost:3000/auth/forgotPassword/f31338c7-981d-43a6-b68c-78cab22948ca
Content-Type: application/json

{
    "username": "test6",
    "password": "working"
}