POST http://localhost:3000/auth/registerAccount
Content-Type: application/json

{
    "username": "tiansien123",
    "email": "tiansien@gmail.com",
    "nickname": "TSgood",
    "password": "123456"
}

###
POST http://localhost:3000/auth/loginAccount
Content-Type: application/json

{
    "email": "sherwynd123@gmail.com",
    "password": "ggwp"
}

###
GET http://localhost:3000/auth/getAccount

###
GET http://localhost:3000/auth/getAccount/f31338c7-981d-43a6-b68c-78cab22948ca
Content-Type: application/json

{
    "refId": "f31338c7-981d-43a6-b68c-78cab22948ca"
}

###
GET http://localhost:3000/auth/getToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic2hlcnd5bmQiLCJpYXQiOjE3MTY2MzEzNDQsImV4cCI6MTcxNjYzNDk0NH0.zTahVoZzBDr4wOlDw21Z5-Q-612ZXqJmBvOjlvOrH28

###
POST http://localhost:3000/auth/refreshToken
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiJ9.dGVzdDY.TdW8dWZigBQcc2UB8eQWwQQHCiGa3pyxQ5-v_OXxY_g"
}

###
PATCH http://localhost:3000/auth/editAccount/65786f07e4ecfebd2945e336
Content-Type: application/json

{

    "username": "sherwynd627",
    "email": "sherwynd627@gmail.com"
}
###

DELETE http://localhost:3000/auth/deleteAccount/6578763b811a538863d71d04

###
DELETE http://localhost:3000/auth/logoutAccount
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiJ9.c2hlcnd5bmQ.WrI9wUZR6r7mhXdvmuN-PfS_8Y7RwBujEkTQLrkQvtw"
}

###

POST http://localhost:3000/auth/forgotPassword
Content-Type: application/json

{
    "email": "sherwynd123@gmail.com"
}

###

GET http://localhost:3000/auth/resetPassword

###

POST http://localhost:3000/auth/resetPassword/1c9b16bb90c4985c04df779a4a1dc59de9f57794
Content-Type: application/json

{
    "password": "123"
}