POST http://localhost:3000/auth/registerAccount
Content-Type: application/json

{
    "username": "test",
    "email": "test1@gmail.com",
    "password": "test"
}

###
POST http://localhost:3000/auth/loginAccount
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "test"
}

###
GET http://localhost:3000/auth/getAccount

###
GET http://localhost:3000/auth/getToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE3MDk5OTYxNzQsImV4cCI6MTcwOTk5NjIwNH0.U2jIYGZE1RsOWUeOknEh5M4MKeyTKN2L4LEPcbf91n8

###
POST http://localhost:3000/auth/refreshToken
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE3MDkxMTA1OTF9.V2JSM4goZqf-w1CXGUmAt4sBHtbOymGPdZ-TQ1BRbtg"
}

###
PATCH http://localhost:3000/auth/editAccount/65786f07e4ecfebd2945e336
Content-Type: application/json

{

    "username": "sherwynd627",
    "email": "sherwynd627@gmail.com"
}
###

DELETE http://localhost:3000/auth/deleteAccount/6578763b811a538863d71d04

###
DELETE http://localhost:3000/auth/logoutAccount
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RBZ2FpbiIsImlhdCI6MTcwMjgwNTkxOX0.EKd16-rY_DjraEzZ4GZUAyxpFdETJTQTq5-NbKPIABI"
}

###

POST http://localhost:3000/auth/forgotPassword
Content-Type: application/json

{
    "email": "test"
}